### ISSUE TITLE
Replacing one deployment host with another does not trigger a reconcile

### ISSUE THREAD

**Issue by Callisto13** [weaveworks-liquidmetal/microvm-operator#25]
start with:

```yaml
kind: MicrovmDeployment
spec:
  hosts:
  - name: host1
    endpoint: 127.0.0.1:9090
```

create.

update to:

```yaml
kind: MicrovmDeployment
spec:
  hosts:
  - name: host2
    endpoint: 127.0.0.1:9091
```

I should see the RS deleted from host1 and a new one created on host2. Right now nothing has noticed that this has changed
