### ISSUE TITLE
Ability to target multiple hosts

### ISSUE THREAD

**Issue by Callisto13** [weaveworks-liquidmetal/microvm-operator#8]
Right now you can only create a microvm on a single host.

It would be good to say "take this spec, create it on these hosts".

Note that this is not about us detecting whether the hosts have capacity, or trying to achieve an even spread of microvms across a pool. This is not "i want to create 10 mvms of the same spec across 3 hosts, figure it out. i expect to end up with 10 total".

This is "i want to create 10 mvms of the same spec on each of these 3 hosts. i expect to end up with 30 total".

If we would rather have the other option (either instead of or as well as), we can create a new ticket.

**Comment by Callisto13** [comment]
```yaml
apiVersion: infrastructure.flintlock.x-k8s.io/v1alpha1
kind: MicrovmDeployment
metadata:
  name: foobar
spec:
  replicas: 10
  hosts:
  - name: host1
    endpoint: 1.2.3.4:9090
  - name: host2
    endpoint: 2.3.4.5:9090
  - name: host3
    endpoint: 3.4.5.6:9090
  template:
    spec:
      sshPublicKeys:
      - user: "root"
        authorizedKeys:
        - "ssh-ed25519 foobar"
      userdata: |
        #!/bin/bash
        echo "hi from my microvm!"
      kernel:
        filename: boot/vmlinux
        image: ghcr.io/weaveworks-liquidmetal/flintlock-kernel:5.10.77
      kernelCmdline: {}
      memoryMb: 2048
      vcpu: 2
      networkInterfaces:
      - guestDeviceName: eth1
        type: macvtap
      rootVolume:
        id: root
        image: ghcr.io/weaveworks-liquidmetal/capmvm-kubernetes:1.21.8
```

Assuming this follows #7, one way to do this would to have the above `MicrovmDeploymentController` create a `MicrovmReplicaSet` per `host`, and then the `MicovmReplicaSetController` creates a `Microvm` per `replica`.

Would that be confusing? Would it be clear that it is multiplicative;  that if I apply the above yaml that I will end up with a total of 30 microvms, 10 per host? Maybe use another keyword other than `replicas`, since we are using it slightly differently to what most people are used to thinking about.

Options:
- `replicasPerHost`
- `countPerHost`

BUT renaming like that does close us off to a future option of having replicas spread around several hosts, something like:

```yaml
spec:
  replicas: 10
  distributeReplicasAcrossHosts: true # or a better name, you get the idea
  hosts:
  - name: host1
    endpoint: 1.2.3.4:9090
  - name: host2
    endpoint: 2.3.4.5:9090
  - name: host3
    endpoint: 3.4.5.6:9090
```

which would place 10 microvms total across 3 hosts. (This is getting ahead a bit, but I don;t want to close that off)
